name: CI, testing, and publishing to NPM

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest']
        node-version: [10.x, 12.x, 13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm audit
      - run: npm test
      - run: npm run setup
      - run: figmagic
      - run: \[ -d figma \]
      - run: \[ -f figma/figma.json \]
        env:
          CI: true

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: git config --global user.email "mikaelvesavuori@gmail.com"
      - run: git config --global user.name "Mikael Vesavuori"
      - run: npm version patch && git add package.json && git add package-lock.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
